// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVL0_zpcEz9KjferhzH38-fz4P3m9o4I0',
    appId: '1:357782052236:web:fa83dba2d5964a0f390aa9',
    messagingSenderId: '357782052236',
    projectId: 'beach-app-d8757',
    authDomain: 'beach-app-d8757.firebaseapp.com',
    storageBucket: 'beach-app-d8757.appspot.com',
    measurementId: 'G-Q7XBRY8EYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmWnhQ-lNHQvCdF96L-S23c76FvbGk0kM',
    appId: '1:357782052236:android:4e486579ddaa9f43390aa9',
    messagingSenderId: '357782052236',
    projectId: 'beach-app-d8757',
    storageBucket: 'beach-app-d8757.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWMBRT-UsEsTCiIVPnPGqrucfyl5RMewc',
    appId: '1:357782052236:ios:c76aaa11c4f5dc57390aa9',
    messagingSenderId: '357782052236',
    projectId: 'beach-app-d8757',
    storageBucket: 'beach-app-d8757.appspot.com',
    iosBundleId: 'com.udhay.beachapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWMBRT-UsEsTCiIVPnPGqrucfyl5RMewc',
    appId: '1:357782052236:ios:b782d032c70069f7390aa9',
    messagingSenderId: '357782052236',
    projectId: 'beach-app-d8757',
    storageBucket: 'beach-app-d8757.appspot.com',
    iosBundleId: 'com.example.beachApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVL0_zpcEz9KjferhzH38-fz4P3m9o4I0',
    appId: '1:357782052236:web:8aea1e47bf134b77390aa9',
    messagingSenderId: '357782052236',
    projectId: 'beach-app-d8757',
    authDomain: 'beach-app-d8757.firebaseapp.com',
    storageBucket: 'beach-app-d8757.appspot.com',
    measurementId: 'G-71Q96PZEPP',
  );
}
